### ISSUE TITLE
API

### ISSUE THREAD

**Issue by Yazeedot** [devinadams/BTC-Machine-Learning-Price-Predictor#1]
when i run code i got ERROR (Status 400) (Quandl Error QEAx01) We could not recognize your API key. Pl
ease check your API key and try again.

I request now api from blockchain 

after that where should I edit it 

also auth token from where can I get the token

thank you

**Comment by devinadams** [comment]
You must register a quandl account and put your API key in the correct spot, it says something like "YOUR AUTH TOKEN HERE". The reason you're getting that error is because it can't grab the data from quandl due to you not having your own API key setup. For the blockchain script "data = quandl.get("BCHAIN/MKPRU", authtoken="YOUR AUTH TOKEN")" change the spot where it says YOUR AUTH TOKEN. On the coinbase script, there's a variable setup called "authtoken" where you place your auth token.
